openapi: 3.0.0
info:
  title: TypeScript Server
  description: An example TypeScript server using Express and Prisma
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /accounts:
    post:
      summary: Create a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ethAddress:
                  type: string
                  pattern: "^0x[a-fA-F0-9]{40}$"
              required:
                - ethAddress
      responses:
        "201":
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "500":
          description: Error occurred while creating the account
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        ethAddress:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
