branch-defaults:
  master:
    environment: ord-swap-service-testnet
  verify-listing:
    environment: ord-swap-service-dev
    group_suffix: null
global:
  application_name: ord-swap-service
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
